apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: cn-docs-test-pipeline-run
  namespace: cn-docs
  labels:
    app: cn-docs
    pipeline: test
spec:
  pipelineRef:
    name: cn-docs-pipeline
  
  params:
    - name: git-url
      value: "https://github.com/Cloud-Native-RS/docs-cloudnative.rs.git"
    - name: git-revision
      value: "main"
    - name: image-repository
      value: "image-registry.openshift-image-registry.svc:5000/cn-docs/cn-docs"
    - name: image-tag
      value: "test-$(date +%s)"
    - name: project-name
      value: "cn-docs"
  
  workspaces:
    - name: shared-workspace
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 1Gi
  
  timeout: 30m
