---
# GitHub Personal Access Token Secret
apiVersion: v1
kind: Secret
metadata:
  name: github-auth-secret
  namespace: cn-docs
  annotations:
    tekton.dev/git-0: https://github.com
type: kubernetes.io/basic-auth
stringData:
  username: "git"  # For token auth, username can be anything
  password: "YOUR_GITHUB_PERSONAL_ACCESS_TOKEN_HERE"
  
---
# Service Account with Git Credentials
apiVersion: v1
kind: ServiceAccount
metadata:
  name: cn-docs-pipeline-sa
  namespace: cn-docs
secrets:
  - name: github-auth-secret
imagePullSecrets:
  - name: github-auth-secret

---
# ClusterRoleBinding for the Service Account
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cn-docs-pipeline-sa-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: edit
subjects:
- kind: ServiceAccount
  name: cn-docs-pipeline-sa
  namespace: cn-docs

---
# Additional permissions for S2I builds
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: cn-docs-pipeline-sa-system-builder
  namespace: cn-docs
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:image-builder
subjects:
- kind: ServiceAccount
  name: cn-docs-pipeline-sa
  namespace: cn-docs
