---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: cn-docs-pipeline-sa
  namespace: cn-docs
  labels:
    app: cn-docs
    pipeline: ci-cd

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: cn-docs-trigger-sa
  namespace: cn-docs
  labels:
    app: cn-docs
    pipeline: ci-cd

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: cn-docs-pipeline-role
  namespace: cn-docs
rules:
  - apiGroups: [""]
    resources: ["pods", "pods/log", "pods/exec", "services", "endpoints", "persistentvolumeclaims", "events", "configmaps", "secrets"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: ["apps"]
    resources: ["deployments", "replicasets"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: ["networking.k8s.io"]
    resources: ["ingresses"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: ["route.openshift.io"]
    resources: ["routes"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: ["project.openshift.io"]
    resources: ["projects"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: ["image.openshift.io"]
    resources: ["imagestreams", "imagestreamtags"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: ["build.openshift.io"]
    resources: ["builds", "buildconfigs"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: ["tekton.dev"]
    resources: ["pipelines", "pipelineruns", "tasks", "taskruns"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: ["triggers.tekton.dev"]
    resources: ["triggertemplates", "triggerbindings", "eventlisteners", "triggers"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: ["triggers.tekton.dev"]
    resources: ["clusterinterceptors", "interceptors"]
    verbs: ["get", "list", "watch"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: cn-docs-trigger-role
  namespace: cn-docs
rules:
  - apiGroups: [""]
    resources: ["pods", "pods/log", "pods/exec", "services", "endpoints", "persistentvolumeclaims", "events", "configmaps", "secrets"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: ["apps"]
    resources: ["deployments", "replicasets"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: ["networking.k8s.io"]
    resources: ["ingresses"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: ["route.openshift.io"]
    resources: ["routes"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: ["project.openshift.io"]
    resources: ["projects"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: ["image.openshift.io"]
    resources: ["imagestreams", "imagestreamtags"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: ["build.openshift.io"]
    resources: ["builds", "buildconfigs"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: ["tekton.dev"]
    resources: ["pipelines", "pipelineruns", "tasks", "taskruns"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: ["triggers.tekton.dev"]
    resources: ["triggertemplates", "triggerbindings", "eventlisteners", "triggers"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: ["triggers.tekton.dev"]
    resources: ["clusterinterceptors", "interceptors"]
    verbs: ["get", "list", "watch"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: cn-docs-pipeline-rolebinding
  namespace: cn-docs
subjects:
  - kind: ServiceAccount
    name: cn-docs-pipeline-sa
    namespace: cn-docs
roleRef:
  kind: Role
  name: cn-docs-pipeline-role
  apiGroup: rbac.authorization.k8s.io

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: cn-docs-trigger-rolebinding
  namespace: cn-docs
subjects:
  - kind: ServiceAccount
    name: cn-docs-trigger-sa
    namespace: cn-docs
roleRef:
  kind: Role
  name: cn-docs-trigger-role
  apiGroup: rbac.authorization.k8s.io
