# Default values for cn-docs
replicaCount: 2

image:
  repository: darioristic/cloud-native-docs
  tag: "latest"
  pullPolicy: Always

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  annotations: {}
  name: ""

podAnnotations: {}

podSecurityContext:
  fsGroup: 1001
  runAsUser: 1001
  runAsGroup: 1001

securityContext:
  capabilities:
    drop:
      - ALL
  readOnlyRootFilesystem: true
  runAsNonRoot: true
  runAsUser: 1001

service:
  type: ClusterIP
  port: 3000

ingress:
  enabled: true
  className: "nginx"
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
  hosts:
    - host: docs.cloudnative.rs
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: cn-docs-tls
      hosts:
        - docs.cloudnative.rs

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 250m
    memory: 256Mi

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 10
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity:
  podAntiAffinity:
    preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 100
        podAffinityTerm:
          labelSelector:
            matchExpressions:
              - key: app.kubernetes.io/name
                operator: In
                values:
                  - cn-docs
          topologyKey: kubernetes.io/hostname

# Environment variables
env:
  NODE_ENV: "production"
  NEXTAUTH_URL: "https://docs.cloudnative.rs"
  NEXTAUTH_SECRET: "lpoOS0yqIpGIzfmSQxzWAu4Ca4WatstrHjThptAzrbw="
  GITHUB_ID: "Ov23liUg8b4ewgeslN3t"
  GITHUB_SECRET: "7d6e7c041a48f8b15400775bd289c8559c2f95ef"
  GITHUB_ORG: "Cloud-Native-RS"
  NEXT_TELEMETRY_DISABLED: "1"

# OpenShift specific configurations
openshift:
  route:
    enabled: true
    host: docs.cloudnative.rs
    tls:
      enabled: true
      termination: edge
      insecureEdgeTerminationPolicy: Redirect
      # certificate: |
      #   -----BEGIN CERTIFICATE-----
      #   ...
      #   -----END CERTIFICATE-----
      # key: |
      #   -----BEGIN PRIVATE KEY-----
      #   ...
      #   -----END PRIVATE KEY-----
